if :x < -30 [
	if :y < 90 [
		right 39
        forward 10
        left 90
        backward 10
	]
	else [
        backward 10
		left 46
	]
] 
if :x < -40 [
	if :y < 90 [
		right 39
        backward 10
	]
	else [
        forward 10
		left 46
        backward 10
	]
] 
if :x < -50 [
	if :y < 90 [
        forward 10
		right 39
	]
	else [
		left 46
	]
] 
if :x < 10 [
	if :y < 90 [
		right 39
        backward 40
	]
	else [
		left 46
	]
] 
if :x < 20 [
	if :y < 90 [
		right 39
        forward 17
	]
	else [
		left 46
	]
] 
if :x < 30 [
	if :y < 90 [
		right 39
	]
	else [
		left 46
	]
] 
if :x < 40 [
	if :y < 90 [
		right 39
        forward 29
	]
	else [
		left 46
        backward 23 
	]
] 
if :x < 50 [
	if :y < 90 [
		right 39
	]
	else [
		left 46
        forward 3
	]
] 